dist: trusty
sudo: required
language:
  - node_js
node_js:
  - "iojs"
  - "7"
  before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
  - sudo add-apt-repository ppa:ubuntu-wine/ppa -y
  - sudo apt-get update
  - sudo apt-get install --no-install-recommends -y wine1.8
cache:
  yarn: true
script:
  - yarn dist
